// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const USER = process.env.POSTGRES_USER;
const PASSWORD = process.env.POSTGRES_PASSWORD;
const DB = process.env.POSTGRES_DB;

export default defineConfig({
  datasource: {
    url: `postgresql://${USER}:${PASSWORD}@localhost:5432/${DB}`,
  },
});
